name: notebook
channels:
  - pytorch
dependencies:
  - torchvision
  - pytorch
  - pillow
  - conda-forge::coremltools=4.0=*_4  # force build 4
  - nbgitpuller
  - conda-forge::xgboost
  - matplotlib
  - pip
  - pip:
    - tensorflow
