name: notebook
channels:
  - pytorch
dependencies:
  - torchvision
  - pytorch
  - pillow
  - conda-forge::coremltools==4.1
  - python-graphviz
  - nbgitpuller
  - conda-forge::xgboost
  - matplotlib
  - pip
  - pip:
    - tensorflow==2.3.1
